name: raspberry_pi_deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RASPBERRY_HOST }}
        username: ${{ secrets.RASPBERRY_USERNAME }}
        password: ${{ secrets.RASPBERRY_PASSWORD }}
        port: ${{ secrets.RASPBERRY_PORT }}
        script: |
          rm -r my-air-app
          git clone https://github.com/vanya-black/my-air-app.git
          source ./my-air-app/raspberry/startup.sh ${{ secrets.S3_HOST }} ${{ secrets.S3_ACCESS_KEY }} ${{ secrets.S3_SECRET_KEY }} ${{ secrets.S3_BUCKET }}