name: raspberry_pi_deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RASPBERRY_HOST }}
        username: ${{ secrets.RASPBERRY_USERNAME }}
        password: ${{ secrets.RASPBERRY_PASSWORD }}
        port: ${{ secrets.RASPBERRY_PORT }}
        script: raspberry/startup.sh