name: raspberry_pi_deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Deploy via ssh
      env:
        S3_HOST: ${{ secrets.S3_HOST }} 
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
      uses: appleboy/ssh-action@master
      with:
        envs: S3_HOST, S3_ACCESS_KEY, S3_SECRET_KEY, S3_BUCKET
        host: ${{ secrets.RASPBERRY_HOST }}
        username: ${{ secrets.RASPBERRY_USERNAME }}
        password: ${{ secrets.RASPBERRY_PASSWORD }}
        port: ${{ secrets.RASPBERRY_PORT }}
        script: |
          rm -r my-air-app
          git clone https://github.com/vanya-black/my-air-app.git
          export S3_HOST=$S3_HOST
          export S3_ACCESS_KEY=$S3_ACCESS_KEY
          export S3_SECRET_KEY=$S3_SECRET_KEY
          export S3_BUCKET=$S3_BUCKET
          source ./my-air-app/raspberry/startup.sh